name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OpenTofu
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/opentofu/opentofu/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
          curl -Lo ./tofu.tar.gz "https://github.com/opentofu/opentofu/releases/download/v${LATEST_VERSION}/tofu_${LATEST_VERSION}_linux_amd64.tar.gz"
          mkdir -p tofu_temp
          tar -xzf tofu.tar.gz -C tofu_temp
          sudo mv tofu_temp/tofu /usr/local/bin/
          rm -rf tofu_temp tofu.tar.gz

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of parent directory:"
          ls -la ..
          echo "Contents of /home/runner/work/deploy-harbor-eks/deploy-harbor-eks:"
          ls -la /home/runner/work/deploy-harbor-eks/deploy-harbor-eks
          echo "Checking if 'tofu' is in PATH:"
          which tofu

      - name: Run tests
        run: |
          cd test
          echo "Current directory after cd:"
          pwd
          echo "Contents of current directory:"
          ls -la
          go test -v ./...
